### ISSUE TITLE
11/26 ) 프로젝트 진행상황

### ISSUE THREAD

**Issue by kjsu0209** [kjsu0209/SpringStudy#2]
여기다 적으면 될듯!!

**Comment by kjsu0209** [comment]
![image](https://user-images.githubusercontent.com/35682236/100310362-5c2c5d80-2ff0-11eb-8bd1-64bf8fd2a804.png)

EC2, RDS 설정 완료!

**Comment by nurungee** [comment]
1. 프론트 수정
2. EC2 설정
완료했고 RDS는 이번주까지 설정 예정!
